### ISSUE TITLE
Catch error for wrong model configuration

### ISSUE THREAD

**Issue by mipmip** [quiqr/quiqr-desktop#288]
```yaml
fields:
  - key: somekey
    title: some wrong configured field
    type: true # should be boolean
    
```

![Screenshot_from_2021-11-26_14-49-33](https://gitlab.brepi.eu/platform/poppygo-electron-app/uploads/4900fd140d9989e11e408025eab66c09/Screenshot_from_2021-11-26_14-49-33.png)
